-- ============================================================================
-- Ah Imobiliária — esquema completo do banco
-- ----------------------------------------------------------------------------
-- Como aplicar: painel do Supabase > SQL Editor > New query > cole isto tudo
-- > Run. É idempotente, pode rodar de novo sem quebrar nada.
--
-- Ordem: extensões > tabelas > índices > triggers > RLS > storage > RPC > seed.
-- ============================================================================

-- No Supabase as extensões moram no schema `extensions`, que já está no
-- search_path. Instalar sem o `with schema` joga no `public` e polui a API.
create extension if not exists pgcrypto  with schema extensions;
create extension if not exists unaccent  with schema extensions;

-- ⚠️ `unaccent()` é STABLE, não IMMUTABLE — as DUAS assinaturas (conferido no
-- Postgres 17.6 deste projeto). Coluna gerada só aceita expressão IMMUTABLE,
-- então usá-la direto falha com "generation expression is not immutable" e
-- derruba o schema inteiro. Este invólucro é o contorno canônico: ele só
-- deixaria de ser verdade se alguém trocasse o dicionário do unaccent, o que
-- não acontece num projeto como este.
create or replace function public.sem_acento(txt text)
returns text
language sql
immutable
strict
parallel safe
as $$ select extensions.unaccent('extensions.unaccent'::regdictionary, txt) $$;

-- Mesma história do `unaccent`, e esta pega quem não esperava: `array_to_string`
-- TAMBÉM é STABLE (ela depende da função de saída do tipo do elemento).
-- Por isso a expressão inteira da busca virou uma função só, declarada
-- IMMUTABLE — é ela que a coluna gerada `imoveis.busca` chama.
create or replace function public.texto_busca(
  p_titulo      text,
  p_bairro      text,
  p_cidade      text,
  p_descricao   text,
  p_comodidades text[]
) returns tsvector
language sql
immutable
parallel safe
as $$
  select to_tsvector(
    'portuguese',
    public.sem_acento(
      coalesce(p_titulo, '')    || ' ' ||
      coalesce(p_bairro, '')    || ' ' ||
      coalesce(p_cidade, '')    || ' ' ||
      coalesce(p_descricao, '') || ' ' ||
      coalesce(array_to_string(p_comodidades, ' '), '')
    )
  )
$$;


-- ============================================================================
-- 1. EQUIPE
-- ----------------------------------------------------------------------------
-- Liga um usuário do Supabase Auth a um perfil público de corretor. Quem não
-- tem linha aqui não é equipe, e portanto não escreve nada no banco.
-- ============================================================================

create table if not exists public.corretores (
  id         uuid primary key references auth.users (id) on delete cascade,
  nome       text not null,
  creci      text,
  -- telefone no formato do link do WhatsApp: só dígitos com DDI. Ex: 5585991225077
  telefone   text,
  email      text,
  foto_url   text,
  admin      boolean not null default false,
  ativo      boolean not null default true,
  criado_em  timestamptz not null default now()
);

comment on table public.corretores is
  'Equipe da imobiliária. Estar aqui = permissão de escrita (ver função e_equipe).';


-- ============================================================================
-- 2. IMÓVEIS
-- ============================================================================

create table if not exists public.imoveis (
  id          uuid primary key default gen_random_uuid(),
  -- código curto e sequencial pro cliente citar no WhatsApp ("quero o 127")
  codigo      integer generated by default as identity unique,

  titulo      text not null,
  finalidade  text not null check (finalidade in ('venda', 'aluguel')),
  tipo        text not null check (tipo in ('casa', 'apartamento', 'terreno', 'comercial', 'rural')),

  preco       numeric(12, 2) not null check (preco >= 0),
  condominio  numeric(12, 2) check (condominio >= 0),
  iptu        numeric(12, 2) check (iptu >= 0),
  aceita_financiamento boolean not null default true,

  quartos     smallint not null default 0 check (quartos >= 0),
  suites      smallint not null default 0 check (suites >= 0),
  banheiros   smallint not null default 0 check (banheiros >= 0),
  vagas       smallint not null default 0 check (vagas >= 0),
  area_util   numeric(10, 2) check (area_util > 0),
  area_total  numeric(10, 2) check (area_total > 0),

  descricao   text,
  -- lista livre: 'piscina', 'churrasqueira', 'portaria 24h', 'mobiliado'...
  comodidades text[] not null default '{}',

  -- localização
  cep         text,
  logradouro  text,
  numero      text,
  complemento text,
  bairro      text not null,
  cidade      text not null,
  uf          char(2) not null default 'CE',
  lat         double precision check (lat between -90 and 90),
  lng         double precision check (lng between -180 and 180),
  -- sigilo do proprietário: quando false, o site mostra só bairro/cidade e o
  -- mapa vira um círculo aproximado em vez de um pino no número exato.
  mostrar_endereco boolean not null default false,

  -- publicação
  status      text not null default 'rascunho'
              check (status in ('rascunho', 'disponivel', 'reservado', 'vendido', 'alugado')),
  destaque    boolean not null default false,
  corretor_id uuid references public.corretores (id) on delete set null,

  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

comment on column public.imoveis.status is
  'rascunho = invisível no site. disponivel/reservado = público. vendido/alugado = fora do ar.';
comment on column public.imoveis.mostrar_endereco is
  'false = site mostra só o bairro. Protege o proprietário de visita sem corretor.';

-- Índices para os filtros que o catálogo realmente usa.
create index if not exists imoveis_publicos_idx  on public.imoveis (status, destaque desc, criado_em desc);
create index if not exists imoveis_filtro_idx    on public.imoveis (finalidade, tipo, cidade, bairro);
create index if not exists imoveis_preco_idx     on public.imoveis (preco);

-- Busca textual em português, acento-insensível.
alter table public.imoveis
  drop column if exists busca;
alter table public.imoveis
  add column busca tsvector generated always as (
    public.texto_busca(titulo, bairro, cidade, descricao, comodidades)
  ) stored;

create index if not exists imoveis_busca_idx on public.imoveis using gin (busca);


-- ============================================================================
-- 3. FOTOS
-- ----------------------------------------------------------------------------
-- O arquivo mora no bucket 'imoveis' do Storage. Aqui fica só o ponteiro.
-- ============================================================================

create table if not exists public.fotos (
  id         uuid primary key default gen_random_uuid(),
  imovel_id  uuid not null references public.imoveis (id) on delete cascade,
  path       text not null,   -- caminho dentro do bucket, ex: '3f2a.../01.webp'
  url        text not null,   -- URL pública já resolvida (o bucket é público)
  ordem      smallint not null default 0,
  legenda    text,
  criado_em  timestamptz not null default now()
);

create index if not exists fotos_imovel_idx on public.fotos (imovel_id, ordem);


-- ---- vídeos ----------------------------------------------------------------
-- Duas naturezas na mesma tabela, separadas por `tipo`:
--   'video'       arquivo nosso, no bucket. `path` preenchido.
--   'video-link'  ponteiro pro YouTube/Instagram/Drive. `path` nulo, e não
--                 ocupa NADA do armazenamento — que é o motivo de existir.
-- Vídeo é o item capaz de estourar o 1 GB do plano free sozinho, então o
-- caminho do link é o preferido e o painel oferece os dois lado a lado.

create table if not exists public.videos (
  id         uuid primary key default gen_random_uuid(),
  imovel_id  uuid not null references public.imoveis (id) on delete cascade,
  tipo       text not null default 'video' check (tipo in ('video', 'video-link')),
  path       text,             -- só em tipo 'video'
  url        text not null,    -- URL pública do arquivo, ou o link colado
  ordem      smallint not null default 0,
  legenda    text,
  criado_em  timestamptz not null default now(),
  -- Arquivo sem caminho no bucket vira lixo impossível de apagar depois.
  constraint videos_path_coerente check (
    (tipo = 'video' and path is not null) or (tipo = 'video-link' and path is null)
  )
);

create index if not exists videos_imovel_idx on public.videos (imovel_id, ordem);


-- ============================================================================
-- 4. LEADS
-- ----------------------------------------------------------------------------
-- Alimentado pelo formulário do site e pelo agente de WhatsApp/Instagram.
-- NUNCA tem leitura pública. Entra só pela RPC registrar_lead().
-- ============================================================================

create table if not exists public.leads (
  id        uuid primary key default gen_random_uuid(),
  nome      text,
  telefone  text,
  email     text,
  origem    text not null default 'site'
            check (origem in ('site', 'whatsapp', 'instagram', 'telefone', 'indicacao', 'portal')),

  -- perfil de busca, preenchido pelo agente durante a qualificação
  finalidade  text check (finalidade in ('venda', 'aluguel')),
  tipo        text,
  bairros     text[] not null default '{}',
  preco_min   numeric(12, 2),
  preco_max   numeric(12, 2),
  quartos_min smallint,
  prazo       text,
  financiamento text,

  mensagem   text,
  resumo     text,   -- resumo da conversa gerado pelo agente
  imovel_id  uuid references public.imoveis (id) on delete set null,

  status     text not null default 'novo'
             check (status in ('novo', 'em_atendimento', 'qualificado', 'visita_agendada', 'proposta', 'fechado', 'perdido')),
  corretor_id uuid references public.corretores (id) on delete set null,

  -- follow-up: a data em que o corretor precisa voltar a falar com esse lead
  proximo_contato date,
  ultimo_contato  timestamptz,

  -- CRM e automacao. canal_id liga a pessoa ao contato do ManyChat/WhatsApp.
  canal_id       text,
  ia_ativa       boolean not null default true,
  prioridade     smallint not null default 1 check (prioridade between 0 and 3),
  valor_potencial numeric(12, 2),
  tags           text[] not null default '{}',
  motivo_perda   text,
  primeira_resposta_em timestamptz,
  qualificado_em timestamptz,
  fechado_em     timestamptz,

  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- Mantem o arquivo idempotente tambem em projetos criados antes do CRM.
alter table public.leads add column if not exists canal_id text;
alter table public.leads add column if not exists ia_ativa boolean not null default true;
alter table public.leads add column if not exists prioridade smallint not null default 1;
alter table public.leads add column if not exists valor_potencial numeric(12, 2);
alter table public.leads add column if not exists tags text[] not null default '{}';
alter table public.leads add column if not exists motivo_perda text;
alter table public.leads add column if not exists primeira_resposta_em timestamptz;
alter table public.leads add column if not exists qualificado_em timestamptz;
alter table public.leads add column if not exists fechado_em timestamptz;

alter table public.leads drop constraint if exists leads_status_check;
alter table public.leads add constraint leads_status_check
  check (status in ('novo', 'em_atendimento', 'qualificado', 'visita_agendada', 'proposta', 'fechado', 'perdido'));

alter table public.leads drop constraint if exists leads_prioridade_check;
alter table public.leads add constraint leads_prioridade_check
  check (prioridade between 0 and 3);

create index if not exists leads_status_idx    on public.leads (status, criado_em desc);
create index if not exists leads_followup_idx  on public.leads (proximo_contato)
  where status not in ('fechado', 'perdido');
create unique index if not exists leads_canal_idx on public.leads (origem, canal_id)
  where canal_id is not null;


-- ============================================================================
-- 5. VISITAS
-- ============================================================================

create table if not exists public.visitas (
  id          uuid primary key default gen_random_uuid(),
  lead_id     uuid references public.leads (id) on delete cascade,
  imovel_id   uuid references public.imoveis (id) on delete set null,
  corretor_id uuid references public.corretores (id) on delete set null,
  quando      timestamptz not null,
  status      text not null default 'agendada'
              check (status in ('agendada', 'confirmada', 'realizada', 'cancelada', 'nao_compareceu')),
  observacao  text,
  criado_em   timestamptz not null default now()
);

create index if not exists visitas_agenda_idx on public.visitas (quando)
  where status in ('agendada', 'confirmada');


-- ============================================================================
-- 5.1 HISTORICO DO LEAD
-- ----------------------------------------------------------------------------
-- Uma linha por mensagem, nota ou mudanca importante. O painel usa esta tabela
-- como linha do tempo e o webhook usa o mesmo historico para manter a conversa
-- da IA mesmo depois de reiniciar o servidor.
-- ============================================================================

create table if not exists public.lead_interacoes (
  id           uuid primary key default gen_random_uuid(),
  lead_id      uuid not null references public.leads (id) on delete cascade,
  tipo         text not null default 'mensagem'
               check (tipo in ('mensagem', 'nota', 'status', 'ia_resumo', 'erro')),
  direcao      text not null default 'interna'
               check (direcao in ('entrada', 'saida', 'interna')),
  autor        text not null default 'sistema'
               check (autor in ('lead', 'corretor', 'ia', 'sistema')),
  canal        text not null default 'painel'
               check (canal in ('site', 'whatsapp', 'instagram', 'telefone', 'indicacao', 'portal', 'painel', 'sistema')),
  conteudo     text not null,
  automatico   boolean not null default false,
  external_id  text,
  lida_em      timestamptz,
  corretor_id  uuid references public.corretores (id) on delete set null,
  metadados    jsonb not null default '{}'::jsonb,
  criado_em    timestamptz not null default now()
);

create index if not exists lead_interacoes_timeline_idx
  on public.lead_interacoes (lead_id, criado_em);
create index if not exists lead_interacoes_nao_lidas_idx
  on public.lead_interacoes (lead_id, criado_em desc)
  where direcao = 'entrada' and lida_em is null;
create unique index if not exists lead_interacoes_externa_idx
  on public.lead_interacoes (canal, external_id)
  where external_id is not null;


-- ============================================================================
-- 5.2 CONFIGURACAO DA IA
-- ----------------------------------------------------------------------------
-- A chave do modelo nunca entra aqui. Ela continua apenas no servidor. Esta
-- tabela guarda controles operacionais que o corretor pode mudar no painel.
-- ============================================================================

create table if not exists public.configuracoes_ia (
  id              text primary key default 'principal',
  modo            text not null default 'automatico'
                  check (modo in ('automatico', 'sugestao', 'desligado')),
  agente          text not null default 'ah_imobiliaria',
  canais          text[] not null default array['whatsapp', 'instagram'],
  mensagem_pausa  text not null default 'Recebi sua mensagem. O corretor vai continuar o atendimento por aqui.',
  atualizado_por  uuid references public.corretores (id) on delete set null,
  atualizado_em   timestamptz not null default now()
);

insert into public.configuracoes_ia (id)
values ('principal')
on conflict (id) do nothing;


-- ============================================================================
-- 6. TRIGGER: atualizado_em
-- ============================================================================

create or replace function public.touch_atualizado_em()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em := now();
  return new;
end;
$$;

drop trigger if exists imoveis_touch on public.imoveis;
create trigger imoveis_touch before update on public.imoveis
  for each row execute function public.touch_atualizado_em();

drop trigger if exists leads_touch on public.leads;
create trigger leads_touch before update on public.leads
  for each row execute function public.touch_atualizado_em();

drop trigger if exists configuracoes_ia_touch on public.configuracoes_ia;
create trigger configuracoes_ia_touch before update on public.configuracoes_ia
  for each row execute function public.touch_atualizado_em();


-- ============================================================================
-- 7. RLS — a única coisa que separa o site do seu pai de um site vandalizado
-- ----------------------------------------------------------------------------
-- A chave anon fica EXPOSTA no JavaScript. Isso é normal e esperado no
-- Supabase. Quem protege os dados são as policies abaixo, não a chave.
-- Se você errar aqui, qualquer visitante deleta a carteira inteira.
-- ============================================================================

-- ⚠️ TODA tabela do public precisa estar nesta lista. Policy escrita numa
-- tabela SEM RLS ligado é simplesmente ignorada pelo Postgres — não dá erro,
-- não avisa, e a tabela fica aberta. Foi o que aconteceu com `videos`, que
-- tinha as duas policies e ficou de fora daqui.
alter table public.corretores enable row level security;
alter table public.imoveis    enable row level security;
alter table public.fotos      enable row level security;
alter table public.videos     enable row level security;
alter table public.leads      enable row level security;
alter table public.visitas    enable row level security;
alter table public.lead_interacoes enable row level security;
alter table public.configuracoes_ia enable row level security;

-- Helper. É SECURITY DEFINER de propósito: ele lê a tabela corretores
-- ignorando o RLS dela. Sem isso, a policy de corretores chamaria uma função
-- que lê corretores, que dispara a policy de novo = recursão infinita
-- (erro 42P17). Esse é o jeito canônico de resolver no Postgres.
create or replace function public.e_equipe()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.corretores c
    where c.id = auth.uid() and c.ativo
  );
$$;

revoke execute on function public.e_equipe() from public;
grant  execute on function public.e_equipe() to authenticated;

-- ---- corretores -----------------------------------------------------------
-- A equipe é pública de propósito: nome, CRECI e telefone do corretor são
-- informação que a imobiliária quer divulgar.
drop policy if exists "equipe visivel para todos"   on public.corretores;
drop policy if exists "corretor edita o proprio perfil" on public.corretores;

create policy "equipe visivel para todos"
  on public.corretores for select
  using (ativo);

create policy "corretor edita o proprio perfil"
  on public.corretores for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- ---- imóveis --------------------------------------------------------------
drop policy if exists "imoveis publicados sao visiveis" on public.imoveis;
drop policy if exists "equipe ve tudo"                  on public.imoveis;
drop policy if exists "equipe escreve imoveis"          on public.imoveis;

-- Visitante anônimo só enxerga o que está no ar. Rascunho, vendido e alugado
-- não vazam nem pela API REST.
create policy "imoveis publicados sao visiveis"
  on public.imoveis for select
  using (status in ('disponivel', 'reservado'));

create policy "equipe ve tudo"
  on public.imoveis for select
  to authenticated
  using (public.e_equipe());

create policy "equipe escreve imoveis"
  on public.imoveis for all
  to authenticated
  using (public.e_equipe())
  with check (public.e_equipe());

-- ---- fotos ----------------------------------------------------------------
drop policy if exists "fotos de imovel publicado" on public.fotos;
drop policy if exists "equipe escreve fotos"      on public.fotos;

create policy "fotos de imovel publicado"
  on public.fotos for select
  using (
    exists (
      select 1 from public.imoveis i
      where i.id = fotos.imovel_id
        and i.status in ('disponivel', 'reservado')
    )
  );

create policy "equipe escreve fotos"
  on public.fotos for all
  to authenticated
  using (public.e_equipe())
  with check (public.e_equipe());

-- ---- vídeos ---------------------------------------------------------------
-- Mesma regra das fotos: visível só enquanto o imóvel estiver publicado.
drop policy if exists "videos de imovel publicado" on public.videos;
drop policy if exists "equipe escreve videos"      on public.videos;

create policy "videos de imovel publicado"
  on public.videos for select
  using (
    exists (
      select 1 from public.imoveis i
      where i.id = videos.imovel_id
        and i.status in ('disponivel', 'reservado')
    )
  );

create policy "equipe escreve videos"
  on public.videos for all
  to authenticated
  using (public.e_equipe())
  with check (public.e_equipe());

-- ---- leads e visitas ------------------------------------------------------
-- Sem policy para anon = ninguém de fora lê nem escreve direto. O site grava
-- lead exclusivamente pela RPC registrar_lead() logo abaixo.
drop policy if exists "equipe gerencia leads"   on public.leads;
drop policy if exists "equipe gerencia visitas" on public.visitas;
drop policy if exists "equipe gerencia interacoes" on public.lead_interacoes;
drop policy if exists "equipe gerencia configuracao ia" on public.configuracoes_ia;

create policy "equipe gerencia leads"
  on public.leads for all
  to authenticated
  using (public.e_equipe())
  with check (public.e_equipe());

create policy "equipe gerencia visitas"
  on public.visitas for all
  to authenticated
  using (public.e_equipe())
  with check (public.e_equipe());

create policy "equipe gerencia interacoes"
  on public.lead_interacoes for all
  to authenticated
  using (public.e_equipe())
  with check (public.e_equipe());

create policy "equipe gerencia configuracao ia"
  on public.configuracoes_ia for all
  to authenticated
  using (public.e_equipe())
  with check (public.e_equipe());

grant select, insert, update, delete on public.lead_interacoes to authenticated;
grant select, insert, update, delete on public.configuracoes_ia to authenticated;
grant all on public.lead_interacoes to service_role;
grant all on public.configuracoes_ia to service_role;


-- ============================================================================
-- 8. STORAGE — bucket das fotos e dos vídeos
-- ============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('imoveis', 'imoveis', true, 52428800,
        array['image/webp', 'image/jpeg', 'image/png',
              'video/mp4', 'video/quicktime', 'video/webm'])
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- 50 MB de teto por arquivo. Era 3 MB, que bastava quando aqui só entrava
-- foto (o admin comprime pra ~200 KB antes de enviar), mas recusava qualquer
-- vídeo. Continua sendo rede de segurança: o painel já barra em 50 MB e
-- oferece o caminho do link, que não gasta armazenamento nenhum.
--
-- ⚠️ Faça a conta antes de encher isto de vídeo: o plano free tem 1 GB no
-- total. Vinte vídeos de 50 MB e acabou o espaço do catálogo inteiro.

drop policy if exists "fotos de imovel sao publicas" on storage.objects;
drop policy if exists "equipe envia fotos"           on storage.objects;
drop policy if exists "equipe troca fotos"           on storage.objects;
drop policy if exists "equipe apaga fotos"           on storage.objects;

create policy "fotos de imovel sao publicas"
  on storage.objects for select
  using (bucket_id = 'imoveis');

create policy "equipe envia fotos"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'imoveis' and public.e_equipe());

create policy "equipe troca fotos"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'imoveis' and public.e_equipe());

create policy "equipe apaga fotos"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'imoveis' and public.e_equipe());


-- ============================================================================
-- 9. RPC — o que o site anônimo pode chamar
-- ============================================================================

-- ---- registrar_lead -------------------------------------------------------
-- Porta única de entrada de lead. SECURITY DEFINER porque anon não tem
-- permissão de INSERT na tabela. Assim o visitante grava um lead sem nunca
-- poder ler, editar ou apagar a base de leads.
create or replace function public.registrar_lead(
  p_nome       text,
  p_telefone   text,
  p_mensagem   text default null,
  p_email      text default null,
  p_imovel_id  uuid default null,
  p_origem     text default 'site'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  -- Validação mínima. O resto de qualidade de dado é problema do corretor.
  if coalesce(trim(p_nome), '') = '' then
    raise exception 'Informe o nome.';
  end if;

  if length(regexp_replace(coalesce(p_telefone, ''), '\D', '', 'g')) < 10 then
    raise exception 'Informe um telefone com DDD.';
  end if;

  if p_origem not in ('site', 'whatsapp', 'instagram', 'telefone', 'indicacao', 'portal') then
    p_origem := 'site';
  end if;

  insert into public.leads (nome, telefone, email, mensagem, imovel_id, origem, proximo_contato)
  values (
    left(trim(p_nome), 120),
    regexp_replace(p_telefone, '\D', '', 'g'),
    nullif(trim(coalesce(p_email, '')), ''),
    left(coalesce(p_mensagem, ''), 2000),
    p_imovel_id,
    p_origem,
    current_date + 1          -- follow-up padrão: cobrar o corretor no dia seguinte
  )
  returning id into v_id;

  if coalesce(trim(p_mensagem), '') <> '' then
    insert into public.lead_interacoes
      (lead_id, tipo, direcao, autor, canal, conteudo, automatico)
    values
      (v_id, 'mensagem', 'entrada', 'lead', p_origem,
       left(trim(p_mensagem), 4000), false);
  end if;

  return v_id;
end;
$$;

grant execute on function public.registrar_lead(text, text, text, text, uuid, text) to anon, authenticated;

-- ---- buscar_imoveis -------------------------------------------------------
-- Usada pelo agente de IA. Devolve poucos campos, já formatados, pra caber no
-- contexto do modelo sem estourar token. O agente passa o perfil do lead e
-- recebe as opções reais da carteira, em vez de inventar imóvel.
create or replace function public.buscar_imoveis(
  p_finalidade text default null,
  p_tipo       text default null,
  p_bairro     text default null,
  p_preco_max  numeric default null,
  p_quartos_min smallint default null,
  p_limite     integer default 5
)
returns table (
  codigo    integer,
  titulo    text,
  tipo      text,
  bairro    text,
  cidade    text,
  preco     numeric,
  quartos   smallint,
  banheiros smallint,
  vagas     smallint,
  area_util numeric
)
language sql
stable
security invoker           -- respeita o RLS: só devolve o que está publicado
set search_path = public
as $$
  select i.codigo, i.titulo, i.tipo, i.bairro, i.cidade, i.preco,
         i.quartos, i.banheiros, i.vagas, i.area_util
  from public.imoveis i
  where i.status in ('disponivel', 'reservado')
    and (p_finalidade  is null or i.finalidade = p_finalidade)
    and (p_tipo        is null or i.tipo       = p_tipo)
    -- public.sem_acento e não unaccent(): esta função roda com
    -- `set search_path = public`, então o schema `extensions` (onde o unaccent
    -- mora) fica fora do caminho aqui dentro.
    -- ⚠️ Casa com BAIRRO **ou** CIDADE de propósito. O agente recebe texto
    -- livre ("tem apartamento em Fortaleza?") e não tem como saber se o que
    -- veio é bairro ou cidade — na prática ele manda a cidade em p_bairro
    -- com frequência. Comparando só com i.bairro, a busca voltava vazia e o
    -- bot respondia "não temos" para um cliente que tinha imóvel disponível.
    -- Visto no app publicado em 11/08/2026. Lead perdido é pior que
    -- resultado amplo demais: aqui o filtro é generoso por escolha.
    and (p_bairro      is null
         or public.sem_acento(i.bairro) ilike '%' || public.sem_acento(p_bairro) || '%'
         or public.sem_acento(i.cidade) ilike '%' || public.sem_acento(p_bairro) || '%')
    and (p_preco_max   is null or i.preco     <= p_preco_max)
    and (p_quartos_min is null or i.quartos   >= p_quartos_min)
  order by i.destaque desc, i.preco asc
  limit least(coalesce(p_limite, 5), 20);
$$;

grant execute on function public.buscar_imoveis(text, text, text, numeric, smallint, integer) to anon, authenticated;


-- ============================================================================
-- 10. VIEW do catálogo — o que o site lê
-- ----------------------------------------------------------------------------
-- Junta a capa e a contagem de fotos numa consulta só, pra listagem não
-- precisar de N+1. security_invoker faz a view respeitar o RLS de imoveis.
-- ============================================================================

create or replace view public.catalogo
with (security_invoker = true)
as
select
  i.id, i.codigo, i.titulo, i.finalidade, i.tipo, i.preco, i.condominio,
  i.quartos, i.suites, i.banheiros, i.vagas, i.area_util, i.comodidades,
  i.bairro, i.cidade, i.uf, i.destaque, i.status, i.criado_em,
  case when i.mostrar_endereco then i.lat else null end as lat,
  case when i.mostrar_endereco then i.lng else null end as lng,
  (select f.url from public.fotos f
    where f.imovel_id = i.id order by f.ordem, f.criado_em limit 1) as capa,
  (select count(*) from public.fotos f where f.imovel_id = i.id)    as total_fotos,
  -- O cartão do catálogo mostra um selo "com vídeo", então a contagem tem que
  -- vir junto: sem isso seria uma consulta por cartão.
  (select count(*) from public.videos v where v.imovel_id = i.id)   as total_videos
from public.imoveis i;

grant select on public.catalogo to anon, authenticated;


-- ============================================================================
-- 11. PRIMEIRO CORRETOR
-- ----------------------------------------------------------------------------
-- Rode DEPOIS de criar o usuário do seu pai em Authentication > Users >
-- Add user. Troque o e-mail abaixo pelo dele e execute só este bloco.
-- Enquanto ninguém estiver em corretores, NINGUÉM consegue escrever nada.
-- ============================================================================

-- insert into public.corretores (id, nome, creci, telefone, email, admin)
-- select u.id, 'Nome do seu pai', 'CRECI-CE 00000', '5585900000000', u.email, true
-- from auth.users u
-- where u.email = 'email-do-seu-pai@exemplo.com'
-- on conflict (id) do update set admin = true, ativo = true;
